### ISSUE TITLE
cant scroll-up after printing hosts file to screen.

### ISSUE THREAD

**Issue by bokunodev** [realh/roxterm#236] opened 2021-05-14 08:29 UTC
i downloaded a hosts file from adaway. but it forgot to redirect its output to a file and print it to the terminal instead.
i have to clear the screen and then i can scroll back up.

**Comment by realh** [comment] 2021-05-15 19:35
I'm not sure I understand what you're describing. Did you download it with something like curl or wget? It sounds like the file contained some weird characters which the terminal interpreted as disabling scrolling.

**Comment by bokunodev** [comment] 2021-05-16 03:10
hi, yes i'm using curl.
i can't scroll-up after printing lots of text to the screen without clearing the terminal (`CTRLl+L`) first.

**Comment by realh** [comment] 2021-05-16 11:29
I tried reproducing this by running `curl https://adaway.org/hosts.txt` but I was still able to scroll. I'm going to ask a lot of questions now, sorry about this. What was the exact command that caused it? Do you only get this problem with that file or with any long series of text? Does it make a difference if you download it to a file and view it with `cat`, compared to what you did before? What versions of roxterm and vte are you using? Are you trying to scroll with a mouse/touchpad or the keyboard shortcuts? What are your profile scrolling options?

**Comment by bokunodev** [comment] 2021-05-16 11:56
@realh no problem.
1. `curl -L adaway.org/hosts.txt`
2. yes, with any long file. log file etc.
3. yes, using `cat` command too.
4. yes, with mouse.
 i set my scrollback limit to **1000**. when i reach the top, it scroll back to the bottom and wont scroll back up. untill i cleared my terminal `(CTRL+L)`.
 both mouse and keyboard scroll is not working.

i can upload my roxterm profile and settings if needed.
i wonder, if my build flags cause it `CFLAGS`.

**Comment by realh** [comment] 2021-05-16 12:22
OK, I can reproduce this by enabling the scrollback limit, but I can also get it to scroll up without resetting by scrolling "more" (with my touchpad . I usually have the limit switched off. I think it's some weird interaction between VteTerminal and GtkScrolledWindow, or it could be another symptom of [GTK/#3752](https://gitlab.gnome.org/GNOME/gtk/-/issues/3752).

**Comment by realh** [comment] 2021-05-16 13:42
I've opened a [vte issue](https://gitlab.gnome.org/GNOME/vte/-/issues/356) for this.

**Comment by bokunodev** [comment] 2021-05-16 15:11
i just take a look at it.
my vte version is `0.64.1-1` (also Arch) and i build roxterm from git (latest).
i build it without kinetic scrolling. from m understanding, kinetic scrolling require patched version of libvte.

**Comment by realh** [comment] 2021-05-16 15:26
The patch got merged into vte by release 0.64. Roxterm can detect whether it's supported at run-time, so it doesn't have any build options to enable it or disable it. It just uses the feature if it can. Maybe I should include an option to disable it, because there are some bugs like this, and kinetic scrolling is only useful for touch pads and touch screens.

**Comment by realh** [comment] 2021-05-16 15:33
If you want to disable it yourself, you can do it by finding this line in `src/roxterm.c`:

`static int roxterm_can_disable_fallback_scrolling = -1;`

Change the -1 to 0.

**Comment by bokunodev** [comment] 2021-05-16 15:52
everything is fine now. it does solve the problem.
should we close this issue ?

**Comment by realh** [comment] 2021-05-18 15:10
I'm reopening, because even though I think it's a VTE bug, I can make some changes to roxterm to mitigate against it.

**Closed** 2021-05-18 16:30 UTC
